** Numerically Accurate Hyperbolic Embeddings Using Tiling-Based Models

Forked from ydtydr/HyperbolicTiling_Learning

This fork contains three more tiling-based models of the hyperbolic space: 
the 3 and 17 dimensionals model based on the polytopes found by Vinberg and the 6 dimensional model based on the polytope found by Bugaenko. 

The Bugenko's polytope are compact.
The 17 and 3 dimensional Vinberg's polytope are not compact but have finite volume.

New options added, e.g:\\
-faraway : initilizes vertices with all (except the first) coordinates close to faraway. 

** Example: 

This shell scripts =train-cora-vinberg3=, =train-mammals-vinberg17.sh=, =train-grqc-bugaenko.sh=, include the appropriate parameter settings for training on mammals, grqc and cora datasets using the new tiling-based models. 

** Installing: 

#+BEGIN_SRC sh
git clone https://github.com/mic-marcinkowski/HyperbolicTiling_Learning.git
cd HyperbolicTiling_Learning
conda env create -f environment.yml
source activate tiling
python setup.py build_ext --inplace
#+END_SRC sh
