** Numerically Accurate Hyperbolic Embeddings Using Tiling-Based Models

This fork contains two more tiling-based models of the hyperbolic space: 
the 17 dimensional model based on the polytope found by Vinberg and the 6 dimensional model based on the polytope found by Bugaenko. 

The Bugenko's polytope is compact and it is the highest-dimensional compact hyperbolic Coxeter polytope known. 
The Vinberg's polytope is not compact but has finite volume and is the highest-dimensional finite volume hyperbolic Coxeter polytope known. 


** Example: Embedding WordNet Mammals
First generate the transitive closure of data via
#+BEGIN_SRC sh
  cd wordnet
  python transitive_closure.py
#+END_SRC
This will generate the transitive closure of the full noun, verb hierarchy as well as of the mammals subtree of WordNet.
We also include the Gr-QC dataset in /wordnet/ folder.

#+END_SRC
This shell script includes the appropriate parameter settings for the mammals subtree. Similar scripts to learn embeddings
of Word nouns, Verbs and Gr-QC are located at =train-nouns.sh=, =train-verbs.sh=,
=train-grqc.sh=. These scripts contain the hyperparameters to reproduce the embeddings results in the paper with available
models: =Poincare=, =Lorentz=, =NLorentz=, =LTiling_rsgd=, =NLTiling_rsgd=, =LTiling_sgd= and =HTiling_rsgd=. Multithreaded async SGD training is also supported.
